spring:
  datasource:
    url: jdbc:mysql://123.57.16.254:13306/dev?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 83ieAp9U+!

    redis:
        host: 192.168.31.231
        port: 6379

server:
  port: 8080

logging:
  config: classpath:logback-spring.xml
  level: debug
