spring:
  datasource:
    url: jdbc:mysql://123.57.16.254:13306/dev?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 83ieAp9U+!

  redis:
    host: 192.168.31.231
    port: 6379

  kafka:
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: 192.168.31.231:9092
    consumer:
      bootstrap-servers: 192.168.31.231:9092
      group-id: foo2
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      max-partition-fetch-bytes: 2
#      max-poll-records: 10

server:
  port: 8080

logging:
  config: classpath:logback-spring.xml
  level: debug
